name: PyLint with dynamic badge

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: Silleellie/pylint-github-action@v2
      with:
        python-version: '3.x'
        lint-path: ArmaDediHelper.py